//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioLab.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ensurance_patients
    {
        public long id { get; set; }
        public long patient { get; set; }
        public long ensurance_account { get; set; }
        public long ensurance { get; set; }
    
        public virtual ensurance ensurance1 { get; set; }
        public virtual patient patient1 { get; set; }
    }
}
