//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioLab.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.ensurance_patients = new HashSet<ensurance_patients>();
            this.research_objects = new HashSet<research_objects>();
        }
    
        public long id { get; set; }
        public string guid { get; set; }
        public string login { get; set; }
        public string full_name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string social_sec_number { get; set; }
        public string ein { get; set; }
        public long social_type { get; set; }
        public string phone { get; set; }
        public Nullable<int> passport_serial { get; set; }
        public Nullable<int> passport_number { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public long country { get; set; }
        public string ip { get; set; }
        public string user_agent { get; set; }
    
        public virtual country country1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ensurance_patients> ensurance_patients { get; set; }
        public virtual social_types social_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<research_objects> research_objects { get; set; }
    }
}
