//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioLab.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_auth_tries
    {
        public long id { get; set; }
        public long user { get; set; }
        public System.DateTime tried_at { get; set; }
        public bool is_success { get; set; }
    
        public virtual user user1 { get; set; }
    }
}
